# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import character_service_pb2 as character__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in character_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CharacterServiceStub(object):
    """------------------- CHARACTER SERVICE -------------------
    Handles character-specific operations separate from login authentication
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCharacterStatus = channel.unary_unary(
                '/sc.external.services.character.v1.CharacterService/GetCharacterStatus',
                request_serializer=character__service__pb2.CharacterStatusRequest.SerializeToString,
                response_deserializer=character__service__pb2.CharacterStatusResponse.FromString,
                _registered_method=True)
        self.GetCharacterData = channel.unary_unary(
                '/sc.external.services.character.v1.CharacterService/GetCharacterData',
                request_serializer=character__service__pb2.CharacterDataRequest.SerializeToString,
                response_deserializer=character__service__pb2.CharacterDataResponse.FromString,
                _registered_method=True)
        self.UpdateCharacterLocation = channel.unary_unary(
                '/sc.external.services.character.v1.CharacterService/UpdateCharacterLocation',
                request_serializer=character__service__pb2.UpdateCharacterLocationRequest.SerializeToString,
                response_deserializer=character__service__pb2.UpdateCharacterLocationResponse.FromString,
                _registered_method=True)


class CharacterServiceServicer(object):
    """------------------- CHARACTER SERVICE -------------------
    Handles character-specific operations separate from login authentication
    """

    def GetCharacterStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCharacterData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateCharacterLocation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CharacterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCharacterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacterStatus,
                    request_deserializer=character__service__pb2.CharacterStatusRequest.FromString,
                    response_serializer=character__service__pb2.CharacterStatusResponse.SerializeToString,
            ),
            'GetCharacterData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCharacterData,
                    request_deserializer=character__service__pb2.CharacterDataRequest.FromString,
                    response_serializer=character__service__pb2.CharacterDataResponse.SerializeToString,
            ),
            'UpdateCharacterLocation': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateCharacterLocation,
                    request_deserializer=character__service__pb2.UpdateCharacterLocationRequest.FromString,
                    response_serializer=character__service__pb2.UpdateCharacterLocationResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sc.external.services.character.v1.CharacterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sc.external.services.character.v1.CharacterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CharacterService(object):
    """------------------- CHARACTER SERVICE -------------------
    Handles character-specific operations separate from login authentication
    """

    @staticmethod
    def GetCharacterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc.external.services.character.v1.CharacterService/GetCharacterStatus',
            character__service__pb2.CharacterStatusRequest.SerializeToString,
            character__service__pb2.CharacterStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCharacterData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc.external.services.character.v1.CharacterService/GetCharacterData',
            character__service__pb2.CharacterDataRequest.SerializeToString,
            character__service__pb2.CharacterDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateCharacterLocation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc.external.services.character.v1.CharacterService/UpdateCharacterLocation',
            character__service__pb2.UpdateCharacterLocationRequest.SerializeToString,
            character__service__pb2.UpdateCharacterLocationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
