# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import config_service_pb2 as config__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in config_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ConfigServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryConfig = channel.unary_unary(
                '/sc.external.services.configuration.v1.ConfigService/QueryConfig',
                request_serializer=config__service__pb2.ConfigRequest.SerializeToString,
                response_deserializer=config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)
        self.WatchConfig = channel.unary_stream(
                '/sc.external.services.configuration.v1.ConfigService/WatchConfig',
                request_serializer=config__service__pb2.ConfigWatchRequest.SerializeToString,
                response_deserializer=config__service__pb2.ConfigResponse.FromString,
                _registered_method=True)


class ConfigServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def QueryConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ConfigServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryConfig,
                    request_deserializer=config__service__pb2.ConfigRequest.FromString,
                    response_serializer=config__service__pb2.ConfigResponse.SerializeToString,
            ),
            'WatchConfig': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchConfig,
                    request_deserializer=config__service__pb2.ConfigWatchRequest.FromString,
                    response_serializer=config__service__pb2.ConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sc.external.services.configuration.v1.ConfigService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sc.external.services.configuration.v1.ConfigService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ConfigService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def QueryConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc.external.services.configuration.v1.ConfigService/QueryConfig',
            config__service__pb2.ConfigRequest.SerializeToString,
            config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/sc.external.services.configuration.v1.ConfigService/WatchConfig',
            config__service__pb2.ConfigWatchRequest.SerializeToString,
            config__service__pb2.ConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
