# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'config_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63onfig_service.proto\x12%sc.external.services.configuration.v1\"R\n\rConfigRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x02 \x01(\t\x12\x16\n\x0e\x63lient_version\x18\x03 \x01(\t\"\xda\x02\n\x0e\x43onfigResponse\x12\x13\n\x0b\x63onfig_data\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x0f\n\x07success\x18\x03 \x01(\x08\x12W\n\tendpoints\x18\x04 \x03(\x0b\x32\x44.sc.external.services.configuration.v1.ConfigResponse.EndpointsEntry\x12U\n\x08\x66\x65\x61tures\x18\x05 \x03(\x0b\x32\x43.sc.external.services.configuration.v1.ConfigResponse.FeaturesEntry\x1a\x30\n\x0e\x45ndpointsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rFeaturesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"V\n\x12\x43onfigWatchRequest\x12\x14\n\x0cservice_name\x18\x01 \x01(\t\x12\x13\n\x0b\x65nvironment\x18\x02 \x01(\t\x12\x15\n\rpoll_interval\x18\x03 \x01(\x05\x32\x8f\x02\n\rConfigService\x12z\n\x0bQueryConfig\x12\x34.sc.external.services.configuration.v1.ConfigRequest\x1a\x35.sc.external.services.configuration.v1.ConfigResponse\x12\x81\x01\n\x0bWatchConfig\x12\x39.sc.external.services.configuration.v1.ConfigWatchRequest\x1a\x35.sc.external.services.configuration.v1.ConfigResponse0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'config_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CONFIGRESPONSE_ENDPOINTSENTRY']._loaded_options = None
  _globals['_CONFIGRESPONSE_ENDPOINTSENTRY']._serialized_options = b'8\001'
  _globals['_CONFIGRESPONSE_FEATURESENTRY']._loaded_options = None
  _globals['_CONFIGRESPONSE_FEATURESENTRY']._serialized_options = b'8\001'
  _globals['_CONFIGREQUEST']._serialized_start=63
  _globals['_CONFIGREQUEST']._serialized_end=145
  _globals['_CONFIGRESPONSE']._serialized_start=148
  _globals['_CONFIGRESPONSE']._serialized_end=494
  _globals['_CONFIGRESPONSE_ENDPOINTSENTRY']._serialized_start=397
  _globals['_CONFIGRESPONSE_ENDPOINTSENTRY']._serialized_end=445
  _globals['_CONFIGRESPONSE_FEATURESENTRY']._serialized_start=447
  _globals['_CONFIGRESPONSE_FEATURESENTRY']._serialized_end=494
  _globals['_CONFIGWATCHREQUEST']._serialized_start=496
  _globals['_CONFIGWATCHREQUEST']._serialized_end=582
  _globals['_CONFIGSERVICE']._serialized_start=585
  _globals['_CONFIGSERVICE']._serialized_end=856
# @@protoc_insertion_point(module_scope)
