# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import identity_service_pb2 as identity__service__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in identity_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IdentityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetIdentity = channel.unary_unary(
                '/sc.external.services.identity.v1.IdentityService/GetIdentity',
                request_serializer=identity__service__pb2.IdentityRequest.SerializeToString,
                response_deserializer=identity__service__pb2.IdentityResponse.FromString,
                _registered_method=True)
        self.VerifyIdentity = channel.unary_unary(
                '/sc.external.services.identity.v1.IdentityService/VerifyIdentity',
                request_serializer=identity__service__pb2.VerifyIdentityRequest.SerializeToString,
                response_deserializer=identity__service__pb2.VerifyIdentityResponse.FromString,
                _registered_method=True)


class IdentityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IdentityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIdentity,
                    request_deserializer=identity__service__pb2.IdentityRequest.FromString,
                    response_serializer=identity__service__pb2.IdentityResponse.SerializeToString,
            ),
            'VerifyIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyIdentity,
                    request_deserializer=identity__service__pb2.VerifyIdentityRequest.FromString,
                    response_serializer=identity__service__pb2.VerifyIdentityResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sc.external.services.identity.v1.IdentityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sc.external.services.identity.v1.IdentityService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IdentityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc.external.services.identity.v1.IdentityService/GetIdentity',
            identity__service__pb2.IdentityRequest.SerializeToString,
            identity__service__pb2.IdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sc.external.services.identity.v1.IdentityService/VerifyIdentity',
            identity__service__pb2.VerifyIdentityRequest.SerializeToString,
            identity__service__pb2.VerifyIdentityResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
