# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: identity_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'identity_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16identity_service.proto\x12 sc.external.services.identity.v1\"<\n\x0fIdentityRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x15\n\rsession_token\x18\x02 \x01(\t\"\x85\x01\n\x10IdentityResponse\x12\x13\n\x0b\x64isplayname\x18\x01 \x01(\t\x12\x10\n\x08nickname\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x11\n\tplayer_id\x18\x04 \x01(\t\x12\x10\n\x08verified\x18\x05 \x01(\x08\x12\x16\n\x0e\x61\x63\x63ount_status\x18\x06 \x01(\t\"?\n\x15VerifyIdentityRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x12\n\nauth_token\x18\x02 \x01(\t\"M\n\x16VerifyIdentityResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tplayer_id\x18\x03 \x01(\t2\x8d\x02\n\x0fIdentityService\x12t\n\x0bGetIdentity\x12\x31.sc.external.services.identity.v1.IdentityRequest\x1a\x32.sc.external.services.identity.v1.IdentityResponse\x12\x83\x01\n\x0eVerifyIdentity\x12\x37.sc.external.services.identity.v1.VerifyIdentityRequest\x1a\x38.sc.external.services.identity.v1.VerifyIdentityResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'identity_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IDENTITYREQUEST']._serialized_start=60
  _globals['_IDENTITYREQUEST']._serialized_end=120
  _globals['_IDENTITYRESPONSE']._serialized_start=123
  _globals['_IDENTITYRESPONSE']._serialized_end=256
  _globals['_VERIFYIDENTITYREQUEST']._serialized_start=258
  _globals['_VERIFYIDENTITYREQUEST']._serialized_end=321
  _globals['_VERIFYIDENTITYRESPONSE']._serialized_start=323
  _globals['_VERIFYIDENTITYRESPONSE']._serialized_end=400
  _globals['_IDENTITYSERVICE']._serialized_start=403
  _globals['_IDENTITYSERVICE']._serialized_end=672
# @@protoc_insertion_point(module_scope)
