# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: presence_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'presence_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16presence_service.proto\x12 sc.external.services.presence.v1\"8\n\x0fPresenceRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\"}\n\x0ePresenceUpdate\x12\x11\n\tplayer_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x10\n\x08\x61\x63tivity\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x11\n\tis_online\x18\x06 \x01(\x08\"_\n\x15UpdatePresenceRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\x12\x10\n\x08\x61\x63tivity\x18\x04 \x01(\t\":\n\x16UpdatePresenceResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x90\x02\n\x0fPresenceService\x12w\n\x0ePresenceStream\x12\x31.sc.external.services.presence.v1.PresenceRequest\x1a\x30.sc.external.services.presence.v1.PresenceUpdate0\x01\x12\x83\x01\n\x0eUpdatePresence\x12\x37.sc.external.services.presence.v1.UpdatePresenceRequest\x1a\x38.sc.external.services.presence.v1.UpdatePresenceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'presence_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRESENCEREQUEST']._serialized_start=60
  _globals['_PRESENCEREQUEST']._serialized_end=116
  _globals['_PRESENCEUPDATE']._serialized_start=118
  _globals['_PRESENCEUPDATE']._serialized_end=243
  _globals['_UPDATEPRESENCEREQUEST']._serialized_start=245
  _globals['_UPDATEPRESENCEREQUEST']._serialized_end=340
  _globals['_UPDATEPRESENCERESPONSE']._serialized_start=342
  _globals['_UPDATEPRESENCERESPONSE']._serialized_end=400
  _globals['_PRESENCESERVICE']._serialized_start=403
  _globals['_PRESENCESERVICE']._serialized_end=675
# @@protoc_insertion_point(module_scope)
