# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: push_service.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'push_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12push_service.proto\x12\x1csc.external.services.push.v1\"F\n\x0bPushRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tplayer_id\x18\x02 \x01(\t\x12\x10\n\x08\x63hannels\x18\x03 \x03(\t\"\xe3\x01\n\x10PushNotification\x12\x17\n\x0fnotification_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x11\n\ttimestamp\x18\x05 \x01(\x03\x12\x46\n\x04\x64\x61ta\x18\x06 \x03(\x0b\x32\x38.sc.external.services.push.v1.PushNotification.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"7\n\x10SubscribeRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63hannel\x18\x02 \x01(\t\"5\n\x11SubscribeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\xe2\x01\n\x0bPushService\x12\x65\n\x06Listen\x12).sc.external.services.push.v1.PushRequest\x1a..sc.external.services.push.v1.PushNotification0\x01\x12l\n\tSubscribe\x12..sc.external.services.push.v1.SubscribeRequest\x1a/.sc.external.services.push.v1.SubscribeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'push_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PUSHNOTIFICATION_DATAENTRY']._loaded_options = None
  _globals['_PUSHNOTIFICATION_DATAENTRY']._serialized_options = b'8\001'
  _globals['_PUSHREQUEST']._serialized_start=52
  _globals['_PUSHREQUEST']._serialized_end=122
  _globals['_PUSHNOTIFICATION']._serialized_start=125
  _globals['_PUSHNOTIFICATION']._serialized_end=352
  _globals['_PUSHNOTIFICATION_DATAENTRY']._serialized_start=309
  _globals['_PUSHNOTIFICATION_DATAENTRY']._serialized_end=352
  _globals['_SUBSCRIBEREQUEST']._serialized_start=354
  _globals['_SUBSCRIBEREQUEST']._serialized_end=409
  _globals['_SUBSCRIBERESPONSE']._serialized_start=411
  _globals['_SUBSCRIBERESPONSE']._serialized_end=464
  _globals['_PUSHSERVICE']._serialized_start=467
  _globals['_PUSHSERVICE']._serialized_end=693
# @@protoc_insertion_point(module_scope)
